name: Test Self-hosted Runner

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted

    steps:
    - name: Print hostname
      run: hostname

    - name: Check kubectl connectivity
      run: |
        kubectl config use-context minikube
        kubectl get nodes
